name: 'Jira ticket extractor'
description: 'Extract jira ticket from any string'
inputs:
  jiraBaseUrl:  # id of input
    description: 'Jira base url'
    required: true
  targetFileName:  # id of input
    description: 'Target file name (Changelog.md by default)'
    required: false

runs:
  using: 'node16'
  main: 'index.js'
