
name: Develop Build
on:
  push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate
      uses: pmuraus/spotlight-changelog-generator-action@main
      with:
        jiraBaseUrl: https://impactwrap.atlassian.net/
        
    - name: Upload
      uses: pmuraus/spotlight-upload-action@main
      with:
        buildName: "Changelog build"
        buildVersion: "1.0"
        files: "./Changelog.md"
        apiKey: ${{secrets.SPOTLIGHT_KEY}}
